### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by ghost** [VinhDuong10998/License-Plate-Recognition#2]
@VinhDuong10998 
upload pretrained model so i can test

**Comment by vinhdc10998** [comment]
thank you for reference. I'm sorry for late replying.
This is model for license plate detection 
https://drive.google.com/file/d/17svijFVfh5j6wqhtJZxn3g7Gx-azafnu/view?usp=sharing

**Comment by ghost** [comment]
Thanks !
